### ISSUE TITLE
Ticket Styling

### ISSUE THREAD

**Issue by srnazng** [HackRU/mentorq#102]
- [x] Uniform styles for each ticket (already sorted into active/closed) - font, font color, ticket color etc. 
- [x] Add styling - [See design mockup for sample](https://www.canva.com/design/DAECJtiS3no/share/preview?token=yVTsAs9_5MSlAUkzYTZWwQ&role=EDITOR&utm_content=DAECJtiS3no&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)

**Comment by chinmaym07** [comment]
Hey @srnazng can I try this .?

**Comment by lucentfong** [comment]
Hi @chinmaym07, I'm glad to see you're interested in MentorQ. At the moment, though this is a public repository, we're only allowing Rutgers students who are a part of HackRU's R&D team to work on the project. If you're a Rutgers student who is interested in joining HackRU as an organizer, feel free to follow our Facebook page https://www.facebook.com/theHackRU and apply to be an organizer during the summer.

**Comment by chinmaym07** [comment]
Sorry I didn't know about it. I am not a student of Rutgers University . 
Thankyou.!! 👍🏻
